### ISSUE TITLE
commons-compress, failure to compile

### ISSUE THREAD

**Issue by djcoin** [wilkerlucio/lein-node-webkit-build#17]
Hi, I'm not an expert in JVM tooling, I asked on the clojure IRC channel, but I will ask it here also!
I have a problem using the plugin, it fails with: 

`clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: org.apache.commons.compress.compressors.xz.XZCompressorInputStream, compiling:(me/raynes/fs/compression.clj:1:1)`

Even though I can import and inspect the library from lein repl:

`(import org.apache.commons.compress.compressors.xz.XZCompressorInputStream)`

Any clue?

Thanks a lot!

**Comment by djcoin** [comment]
Ok, problem solved, confusing dependencies, I had to add:

`[lein-cljsbuild "1.1.2" :exclusions [org.apache.commons/commons-compress]]`

**Comment by wilkerlucio** [comment]
@djcoin cool, I'm glad to hear that you find the fix.
